// Tauri 构建脚本入口：负责生成构建期上下文与打包所需元数据。
// 额外处理一个工程化细节：当仓库里没有保留 dist/ 时，纯 Rust 的 cargo test
// 也需要一个最小 frontendDist 占位目录，否则 generate_context! 会在编译期失败。

use std::{env, fs, path::PathBuf};

fn main() {
    ensure_placeholder_frontend_dist();
    tauri_build::build();
}

fn ensure_placeholder_frontend_dist() {
    let manifest_dir = match env::var("CARGO_MANIFEST_DIR") {
        Ok(value) => PathBuf::from(value),
        Err(_) => return,
    };

    let dist_dir = manifest_dir.join("..").join("dist");
    let index_path = dist_dir.join("index.html");
    if index_path.exists() {
        return;
    }

    let _ = fs::create_dir_all(&dist_dir);
    let _ = fs::write(
        index_path,
        "<!doctype html><html><head><meta charset=\"utf-8\"><title>Smart Clipboard placeholder</title></head><body>Frontend assets are generated by npm run build.</body></html>",
    );
}
