const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 960, height: 640 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const items = Array.from({length: 40}, (_, i) => {
    const lead = `Record ${i} preview`;
    const content = i === 1 ? ('course,version,text_source,root_duration_min,leaf_source_coverage,invalid_source_id_count,playback_assignment_mismatch_count\n'.repeat(30)) + `END-${i}` : `### Record ${i}\n\n` + ('Long paragraph 中文内容 https://example.com/verylonglink 文本换行测试。\n\n'.repeat(30)) + `END-${i}`;
    return {id: `test-${i}`, kind: 'text', content, preview: lead + 'x'.repeat(180 - lead.length) + '...', isStar: false, createdAt: 1780000000, updatedAt: 1780000000};
  });
  items.push({id:'short-text', kind:'text', content:'short text', preview:'short text', isStar:false, createdAt:1780000000, updatedAt:1780000000});
  items[0].folderId = 'demo-folder';
  items[1].folderId = 'demo-folder';
  const imageBase64 = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl7hSAAAAAASUVORK5CYII=';
  items.push({id:'short-ocr',kind:'image',imagePath:imageBase64,preview:'short ocr image',ocrText:'one line',isStar:false,createdAt:1780000000,updatedAt:1780000000});
  items.push({id:'long-ocr',kind:'image',imagePath:imageBase64,preview:'long ocr image',ocrText:'first line\nsecond line\nthird line\nfourth line\nfifth line\nsixth line',isStar:false,createdAt:1780000000,updatedAt:1780000000});
  await page.route('**/src/tauriClient.ts', async route => {
    const response = await route.fetch();
    let body = await response.text();
    body = body.replace(/const demoItems = \[[\s\S]*?\n\];/, `const demoItems = ${JSON.stringify(items)};`);
    body = body.replace('export async function onNewItem(callback) {', 'export async function onNewItem(callback) { window.__newClipboardItem = callback;');
    body = body.replace('export async function call(command, args) {', `export async function call(command, args) {
      window.__uiCalls = window.__uiCalls || [];
      window.__uiCalls.push(command);
      if (command === 'save_app_settings') { window.__lastSettingsSave = args.settings; window.__persistedSettings = args.settings; }
      if (command === 'get_app_settings' && window.__persistedSettings) return window.__persistedSettings;
      if (command === 'change_data_directory' && args.settings.dataDirectory === 'relative/bad?path') throw new Error('Invalid data directory: unsupported folder name');
      if (command === 'test_ai_connection') window.__lastAiTestSettings = args.settings;
      if (command === 'list_ai_models') window.__lastModelSettings = args.settings;
      if (command === 'get_folders') return [{id:'demo-folder', name:'Existing folder', createdAt:1780000000}];
      if (command === 'create_folder') return {id:'new-folder', name:args.name, createdAt:1780000000};
      if (command === 'search_ai_semantic') {
        await new Promise(resolve => setTimeout(resolve, args.query === 'stale-error' ? 350 : 30));
        if (args.query === 'stale-error' || args.query === 'live-error') throw new Error(args.query);
        return ['test-0'];
      }
      if (command === 'search_local_light') {
        await new Promise(resolve => setTimeout(resolve, args.keyword === 'slow-old' ? 600 : 30));
        return demoItems.filter(item => (item.content + item.preview).includes(args.keyword)).map(({content, ...item}) => item);
      }
    `);
    await route.fulfill({ response, body });
  });
  await page.goto(process.env.UI_TEST_URL || 'http://127.0.0.1:1420');
  await page.locator('.historyItem').first().waitFor();
  async function checkLayout(label) {
    await page.waitForTimeout(180);
    const rows = await page.locator('.historyRow').evaluateAll(nodes => nodes.map(node => ({index: Number(node.dataset.index), top: node.getBoundingClientRect().top, bottom: node.getBoundingClientRect().bottom, articleBottom: node.firstElementChild.getBoundingClientRect().bottom})).sort((a,b)=>a.index-b.index));
    for (let i = 1; i < rows.length; i++) {
      assert.ok(Math.abs(rows[i].top - rows[i-1].bottom) < 1, `${label}: row gap/overlap ${JSON.stringify(rows.slice(i-1,i+1))}`);
      assert.ok(rows[i].top - rows[i-1].articleBottom >= 9.5, `${label}: missing spacing`);
    }
    console.log('PASS', label, rows.length, 'mounted rows');
  }
  await checkLayout('initial');
  const compactHeights = await page.locator('.recordContent.isTruncated').evaluateAll(nodes => nodes.slice(0, 2).map(node => node.getBoundingClientRect().height));
  assert.deepEqual(compactHeights, [148, 148], 'Markdown and plain text must have the same compact height');
  assert.ok(await page.locator('.recordContent.isTruncated .recordPreviewText').first().evaluate(el => getComputedStyle(el).fontSize === '14px'), 'compact preview must use normal text size');
  const first = page.locator('.historyItem').first();
  await first.getByRole('button', {name:'展开全部'}).click();
  await page.waitForFunction(() => document.querySelector('.recordContent.expanded')?.textContent.includes('END-0'));
  assert.ok(await page.locator('.recordContent.expanded').first().evaluate(el => el.clientHeight > 220));
  assert.equal(await first.locator('.recordCollapseButton .lucide-chevron-up').count(), 1, 'text collapse must use a clear upward icon');
  await checkLayout('expand fetched full text');
  await first.getByRole('button', {name:'收起'}).click();
  assert.ok(await page.locator('.recordContent').first().evaluate(el => el.clientHeight <= 220));
  assert.ok(await page.locator('.recordContent.isTruncated').first().evaluate(el=>getComputedStyle(el,'::after').backgroundImage.includes('linear-gradient')));
  await checkLayout('collapse long text');
  await first.getByRole('button', {name:'展开全部'}).focus();
  await page.keyboard.press('Enter');
  await checkLayout('keyboard expand');
  await first.getByRole('button', {name:'收起'}).click();
  await page.setViewportSize({width:760, height:520});
  await checkLayout('narrow window');
  await page.getByTitle('折叠侧边栏').click();
  await checkLayout('sidebar width change');
  await page.locator('.historyList').evaluate(el => el.scrollTop = 1800);
  await checkLayout('virtual scroll');
  await page.getByPlaceholder('搜索剪贴板', {exact:true}).fill('Record 2');
  await page.waitForTimeout(400);
  await checkLayout('filtered indices');
  await page.getByPlaceholder('搜索剪贴板', {exact:true}).fill('');
  await page.waitForTimeout(400);
  await checkLayout('restore history');
  await page.locator('.historyItem').first().locator('.recordRevealButton').click();
  await page.locator('.historyList').evaluate(el => { el.scrollTop = 250; });
  await page.waitForTimeout(120);
  const scrollBeforeManualClose = await page.locator('.historyList').evaluate(el => el.scrollTop);
  assert.ok(scrollBeforeManualClose > 0, 'manual-close test must start below the top');
  await page.keyboard.press('Escape');
  await page.evaluate(() => window.dispatchEvent(new Event('smart-clipboard-panel-shown')));
  await page.waitForTimeout(80);
  const manualHideCount = await page.evaluate(() => window.__uiCalls.filter(command => command === 'hide_window').length);
  assert.equal(await page.locator('.historyList').evaluate(el => el.scrollTop), scrollBeforeManualClose, 'manual close preserves scroll position');
  assert.equal(await page.locator('.recordContent.expanded').count(), 1, 'manual close preserves expanded records');
  await page.locator('.historyItem').first().locator('.pasteTarget').click();
  await page.waitForFunction(() => document.querySelector('.historyList')?.scrollTop === 0 && document.querySelectorAll('.recordContent.expanded').length === 0);
  assert.ok(await page.evaluate(() => window.__uiCalls.includes('execute_paste')), 'paste action must run before resetting the view');
  console.log('PASS manual close preserves view; successful paste resets scroll and expansion');
  await page.locator('.historyList').evaluate(el => el.scrollTop = 0);
  await page.evaluate(item => window.__newClipboardItem(item), {...items[0], id:'new-record'});
  await checkLayout('prepend full long record');
  assert.ok(await page.locator('.recordContent').first().evaluate(el => el.clientHeight <= 220));
  await page.locator('.historyItem').first().getByRole('button', {name:'展开全部'}).click();
  await checkLayout('expand new record');
  await page.locator('.historyItem').first().getByRole('button', {name:'收起'}).click();
  await page.evaluate(item => window.__newClipboardItem(item), items[20]);
  await checkLayout('existing record moved to front');
  const search = page.locator('.searchBox input');
  await search.fill('END-25');
  await page.waitForTimeout(400);
  assert.equal(await page.locator('.historyItem').count(), 1, 'full-content search must survive missing preview match');
  assert.ok((await page.locator('.historyItem').innerText()).includes('Record 25 preview'));
  await search.fill('slow-old');
  await page.waitForTimeout(300);
  await search.fill('END-26');
  await page.waitForTimeout(900);
  assert.ok((await page.locator('.historyItem').innerText()).includes('Record 26 preview'), 'stale response must not replace new results');
  await search.fill('slow-old');
  await page.waitForTimeout(300);
  await page.locator('.searchClearButton').click();
  await page.waitForTimeout(800);
  assert.ok(await page.locator('.historyItem').count() > 1, 'clear search must invalidate pending requests');
  console.log('PASS full-text matches, response race, clear race');
  await search.fill('short text');
  await page.waitForTimeout(400);
  assert.equal(await page.locator('.recordRevealButton').count(),0,'short text must not have expand control');
  assert.equal(await page.locator('.recordContent.isTruncated').count(),0,'short text must not fade');
  await search.fill('short ocr image');
  await page.waitForTimeout(400);
  assert.equal(await page.locator('.ocrRevealButton').count(),0,'short OCR must not have expand control');
  await search.fill('long ocr image');
  await page.waitForTimeout(400);
  await page.locator('.ocrRevealButton').waitFor();
  assert.ok(await page.locator('.ocrRevealButton').evaluate(el => el.getBoundingClientRect().width < 50), 'OCR reveal must be smaller than the text reveal');
  await page.locator('.ocrRevealButton').click();
  assert.ok(await page.locator('.ocrTextPane').first().evaluate(el=>el.clientHeight>126));
  assert.ok(await page.locator('.imageCard.ocrExpanded').evaluate(el => {
    const image = el.querySelector('.imagePreviewPane').getBoundingClientRect();
    const text = el.querySelector('.ocrTextPane').getBoundingClientRect();
    return text.top > image.bottom && text.width >= el.getBoundingClientRect().width - 35;
  }), 'expanded OCR must show full-width text below the image');
  const thumbnail = page.locator('.imageThumbButton');
  assert.equal(await thumbnail.getAttribute('title'), '完整预览');
  await thumbnail.click();
  assert.equal(await thumbnail.getAttribute('title'), '停止预览');
  assert.ok(await page.locator('.imageCard.ocrExpanded').evaluate(el => {
    const image = el.querySelector('.imagePreviewPane').getBoundingClientRect();
    const preview = el.querySelector('.inlineImagePreview').getBoundingClientRect();
    const text = el.querySelector('.ocrTextPane').getBoundingClientRect();
    const collapse = el.querySelector('.ocrCollapseButton').getBoundingClientRect();
    return preview.top >= image.bottom && text.top > preview.bottom && collapse.top >= image.top && collapse.bottom <= image.bottom;
  }), 'image preview must sit below image and above OCR text while collapse stays inside the image area');
  assert.equal(await page.locator('.ocrCollapseButton').getAttribute('aria-label'), '收起 OCR 文字');
  await page.screenshot({path:path.join(os.tmpdir(), 'smart-clipboard-ocr-review.png')});
  await page.locator('.ocrCollapseButton').click();
  assert.ok(await page.locator('.imageCard.withOcr').evaluate(el => !el.classList.contains('ocrExpanded') && !!el.querySelector('.inlineImagePreview')), 'collapsing OCR restores side-by-side layout while retaining image preview');
  await thumbnail.click();
  assert.equal(await thumbnail.getAttribute('title'), '完整预览');
  console.log('PASS short text/OCR omit controls; long text/OCR reveal and collapse');
  const glassButton = page.locator('.iconButton').first();
  const bounds = await glassButton.boundingBox();
  await page.mouse.move(bounds.x + 4, bounds.y + 4);
  const firstGlint = await glassButton.evaluate(el=>el.style.getPropertyValue('--glint-x'));
  await page.mouse.move(bounds.x + bounds.width - 4, bounds.y + 4);
  const secondGlint = await glassButton.evaluate(el=>el.style.getPropertyValue('--glint-x'));
  assert.ok(firstGlint && secondGlint && firstGlint !== secondGlint,'glass highlight must follow pointer');
  console.log('PASS pointer-following glass highlight');
  await page.setViewportSize({width:960, height:640});
  await page.getByTitle('折叠侧边栏').click();
  const existingFolder = page.locator('.folderBlock').first();
  assert.equal((await existingFolder.locator('.countBadge').innerText()).trim(), '2', 'folder count must use all records while search is filtered');
  await existingFolder.locator('.folderHeader').click();
  assert.equal(await existingFolder.locator('.folderRecordRow').count(), 2, 'folder contents must remain visible while the timeline is filtered');
  await page.getByTitle('新建文件夹').click();
  await page.getByRole('dialog', {name:'新建文件夹'}).waitFor();
  await page.waitForTimeout(280);
  await page.screenshot({path:path.join(os.tmpdir(), 'smart-clipboard-folder-dialog-review.png')});
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(), 0, 'Escape closes the folder dialog');
  assert.equal(await page.evaluate(() => window.__uiCalls.filter(command => command === 'hide_window').length), manualHideCount, 'folder dialog Escape must not hide the app');
  await page.getByTitle('新建文件夹').click();
  await page.getByRole('dialog').getByPlaceholder('文件夹名称').fill('UI review');
  await page.getByRole('dialog').getByRole('button', {name:'新建文件夹'}).click();
  assert.equal(await page.locator('.folderBlock').count(), 2, 'glass folder dialog creates a folder');
  console.log('PASS global folder contents and glass creation dialog');
  await page.locator('.settingsSection .sectionHeader').click();
  await page.screenshot({path:path.join(os.tmpdir(), 'smart-clipboard-settings-review.png')});
  const languageSelect = page.locator('.settingsSection .glassSelect').first();
  await languageSelect.scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(os.tmpdir(), 'smart-clipboard-settings-controls-review.png')});
  await languageSelect.getByRole('combobox').click();
  assert.equal(await languageSelect.getByRole('option').count(), 2, 'language choices must use the custom glass menu');
  await page.keyboard.press('Escape');
  assert.equal(await languageSelect.getByRole('option').count(), 0, 'Escape closes only the dropdown');
  assert.equal(await page.evaluate(() => window.__uiCalls.filter(command => command === 'hide_window').length), manualHideCount, 'dropdown Escape must not close the app');
  await languageSelect.getByRole('combobox').click();
  await languageSelect.getByRole('option', {name:'EN'}).click();
  assert.equal(await languageSelect.getByRole('combobox').getAttribute('aria-expanded'), 'false');
  await languageSelect.getByRole('combobox').click();
  await languageSelect.getByRole('option', {name:'中文'}).click();
  await page.locator('.settingsActions .feedbackButton').first().click();
  await page.locator('.settingsActions .feedbackButton.isSuccess').first().waitFor();
  assert.ok((await page.locator('.settingsActions .feedbackButton').first().innerText()).includes('已保存'));
  assert.equal(await page.locator('.pathApplyButton.isSuccess').count(), 0, 'saving settings must not alter path apply feedback');
  assert.equal(await page.locator('.settingsStatus').count(), 0, 'successful save must not add bottom status text');
  await page.locator('.settingsActions .feedbackButton').nth(1).click();
  await page.locator('.settingsActions .feedbackButton').nth(1).locator('.feedbackLabel').getByText('测试成功').waitFor();
  assert.equal(await page.locator('.settingsStatus').count(), 0, 'test feedback must remain inside its button');
  await page.locator('.settingsActions .feedbackButton').nth(2).click();
  await page.locator('.settingsActions .feedbackButton').nth(2).locator('.feedbackLabel').getByText('已加载 3 个模型').waitFor();
  assert.equal(await page.locator('.settingsStatus').count(), 0, 'model feedback must remain inside its button');
  const modelField = page.locator('.modelInput');
  await modelField.locator('input').click();
  await modelField.getByRole('button', {name:'收起模型候选'}).click();
  assert.equal(await modelField.getByRole('option').count(), 0, 'model button collapses the candidate list');
  await modelField.getByRole('button', {name:'显示模型候选'}).click();
  assert.equal(await modelField.getByRole('option').count(), 3, 'model button reopens the full candidate list');
  await page.screenshot({path:path.join(os.tmpdir(), 'smart-clipboard-model-options-review.png')});
  await modelField.getByRole('button', {name:'收起模型候选'}).click();
  assert.ok(await page.locator('.pathApplyButton').evaluate(el => getComputedStyle(el).color !== 'rgb(255, 255, 255)'), 'disabled path button must have readable text');
  const pendingPath = page.locator('.dataDirectoryField input');
  await pendingPath.fill('E:/PendingReview');
  await page.locator('.dataDirectoryField .fieldHelp').first().click();
  assert.equal(await pendingPath.evaluate(el => document.activeElement === el), false, 'clicking path help must blur the path input');
  await pendingPath.click();
  await page.locator('.dataDirectoryField').click({position:{x:5,y:5}});
  assert.equal(await pendingPath.evaluate(el => document.activeElement === el), false, 'clicking path section outside input must blur it');
  const openaiInput = page.locator('.fieldLabel input').first();
  await openaiInput.click();
  await openaiInput.locator('..').click({position:{x:5,y:5}});
  assert.equal(await openaiInput.evaluate(el => document.activeElement === el), false, 'clicking a text field title must blur its input');
  await openaiInput.fill('https://draft.example/v1');
  const toggleInputs = page.locator('.toggleRow input');
  const savesBeforeToggles = await page.evaluate(() => window.__uiCalls.filter(command => command === 'save_app_settings').length);
  await toggleInputs.nth(0).uncheck();
  await toggleInputs.nth(0).evaluate(el => el.disabled ? new Promise(resolve => {
    const observer = new MutationObserver(() => { if (!el.disabled) { observer.disconnect(); resolve(); } });
    observer.observe(el, {attributes:true});
  }) : undefined);
  await toggleInputs.nth(1).check();
  await toggleInputs.nth(1).evaluate(el => el.disabled ? new Promise(resolve => {
    const observer = new MutationObserver(() => { if (!el.disabled) { observer.disconnect(); resolve(); } });
    observer.observe(el, {attributes:true});
  }) : undefined);
  await toggleInputs.nth(2).uncheck();
  await page.waitForFunction(count => window.__uiCalls.filter(command => command === 'save_app_settings').length === count + 3, savesBeforeToggles);
  assert.equal(await page.evaluate(() => window.__lastSettingsSave.captureEnabled), false, 'capture switch saves immediately');
  assert.equal(await page.evaluate(() => window.__lastSettingsSave.runAtStartup), true, 'startup switch saves immediately');
  assert.equal(await page.evaluate(() => window.__lastSettingsSave.hideConsoleWindow), false, 'console switch saves immediately');
  assert.equal(await openaiInput.inputValue(), 'https://draft.example/v1', 'switch saves must preserve unrelated text drafts');
  assert.equal(await page.evaluate(() => window.__lastSettingsSave.openaiBaseUrl), 'https://api.xiaomimimo.com/v1', 'switch saves must not commit unrelated text drafts');
  await page.locator('.secretRow input').fill('review-api-key');
  await page.locator('.settingsActions .feedbackButton').nth(1).click();
  await page.locator('.settingsActions .feedbackButton').nth(1).locator('.feedbackLabel').getByText('测试成功').waitFor();
  assert.equal(await pendingPath.inputValue(), 'E:/PendingReview', 'testing AI must preserve the pending directory in the form');
  assert.equal(await page.evaluate(() => window.__lastSettingsSave.dataDirectory), '', 'testing AI must not persist a directory change without migration');
  assert.equal(await page.evaluate(() => window.__lastSettingsSave.captureEnabled), false, 'testing AI preserves the already saved capture switch');
  assert.equal(await page.evaluate(() => window.__lastSettingsSave.runAtStartup), true, 'testing AI preserves the already saved startup switch');
  assert.equal(await page.evaluate(() => window.__lastSettingsSave.apiKey), 'review-api-key', 'testing AI saves the current API key');
  assert.equal(await page.evaluate(() => window.__lastAiTestSettings.apiKey), 'review-api-key', 'connection test uses the saved API key');
  assert.equal(await page.locator('.toggleRow input').first().isChecked(), false, 'saved capture toggle stays in the form');
  assert.equal(await page.locator('.pathApplyButton').isDisabled(), false, 'path migration button must remain available');
  await page.locator('.secretRow input').fill('unsaved-model-key');
  const savesBeforeModels = await page.evaluate(() => window.__uiCalls.filter(command => command === 'save_app_settings').length);
  await page.locator('.settingsActions .feedbackButton').nth(2).click();
  await page.locator('.settingsActions .feedbackButton').nth(2).locator('.feedbackLabel').getByText('已加载 3 个模型').waitFor();
  assert.equal(await page.evaluate(() => window.__uiCalls.filter(command => command === 'save_app_settings').length), savesBeforeModels, 'listing models must not save settings');
  assert.equal(await page.evaluate(() => window.__lastModelSettings.apiKey), 'unsaved-model-key', 'model list uses the current unsaved API key');
  await pendingPath.fill('E:/UnsavedOnClose');
  await openaiInput.fill('https://unsaved-on-close.example/v1');
  await page.evaluate(() => window.dispatchEvent(new Event('smart-clipboard-panel-shown')));
  await page.waitForFunction(() => document.querySelector('.dataDirectoryField input')?.value === '');
  assert.equal(await openaiInput.inputValue(), 'https://draft.example/v1', 'reopening restores the last saved URL');
  assert.equal(await pendingPath.inputValue(), '', 'reopening discards the uncommitted path');
  await pendingPath.fill('relative/bad?path');
  await page.evaluate(() => { window.confirm = () => true; });
  const restartsBeforeInvalidPath = await page.evaluate(() => window.__uiCalls.filter(command => command === 'restart_application').length);
  await page.locator('.pathApplyButton').click();
  await page.locator('.pathApplyButton.isError').waitFor();
  assert.equal((await page.locator('.pathApplyButton .feedbackLabel').innerText()).trim(), '路径无效', 'invalid path failure appears in its own button');
  assert.equal(await page.locator('.pathError').count(), 0, 'path failure has no separate message below the button');
  assert.equal(await page.evaluate(() => window.__uiCalls.filter(command => command === 'restart_application').length), restartsBeforeInvalidPath, 'invalid path cannot restart the app');
  console.log('PASS glass dropdown and in-button settings feedback');
  await page.getByTitle('LLM 语义搜索').click();
  const aiInput = page.getByPlaceholder('AI 搜索剪贴板');
  await aiInput.fill('stale-error');
  await page.getByTitle('运行 AI 搜索').click();
  await aiInput.fill('new-query');
  await page.waitForTimeout(450);
  assert.equal(await page.locator('.statusLine').count(), 0, 'stale AI error and loading notice must clear after changing the query');
  await page.getByTitle('运行 AI 搜索').click();
  await page.locator('.statusLine.success').waitFor();
  assert.equal(await page.locator('.statusLine[role="status"] .lucide-circle-check').count(), 1, 'successful search uses glass success notification');
  assert.equal(await page.locator('.statusLine.success .statusClose').getAttribute('aria-label'), '关闭通知');
  await page.screenshot({path:path.join(os.tmpdir(), 'smart-clipboard-notice-review.png')});
  await aiInput.fill('live-error');
  await page.getByTitle('运行 AI 搜索').click();
  await page.locator('.statusLine.error').waitFor();
  assert.equal(await page.locator('.statusLine.error').getAttribute('role'), 'alert');
  console.log('PASS notification theme and stale AI search feedback');
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('.historyItem').first().evaluate(el => getComputedStyle(el).transitionDuration), '0s');
  console.log('PASS reduced motion');
  assert.deepEqual(errors, []);
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
